name: espalier
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - numpy=2.4.3
  - scipy=1.17.1
  - matplotlib
  - pandas=3.0.1
  - seaborn
  - spyder
  - biopython=1.86
  - dendropy=5.0.8
  - tskit=1.0.2
  - click=8.3.1
  - msprime=1.4.1
